### ISSUE TITLE
where .env file?

### ISSUE THREAD

**Issue by lordmen99** [ppenter/fontpad#1]
i try setup local still show error.

**Comment by lordmen99** [comment]
get this error 

`×
TypeError: Cannot read properties of undefined (reading 'address')
Footer
src/components/Footer/Footer.js:32
  29 | <p>IDO Factory: </p>
  30 | <FooterLink
  31 |   target="_blank"
> 32 |   href={
     | ^  33 |     process.env.REACT_APP_Explorer +
  34 |     "address/" +
  35 |     IDOFactory.networks[process.env.REACT_APP_networkID].address`

**Comment by ppenter** [comment]
> get this error
> 
> `× TypeError: Cannot read properties of undefined (reading 'address') Footer src/components/Footer/Footer.js:32 29 |
> 
> IDO Factory:
> 
> 
> 30 | <FooterLink
> 31 | target="_blank"
> > 32 |   href={
> > | ^  33 |     process.env.REACT_APP_Explorer +
> > 34 |     "address/" +
> > 35 |     IDOFactory.networks[process.env.REACT_APP_networkID].address`

You need to deploy smart contract first or wait for me. I will wrap it up to check whether or not the contract deployed.

**Comment by ppenter** [comment]
@lordmen99 Just update env.example file. #0c92cabc1ebfebf7a5038eed939a4b6c124ea36b

**Comment by ppenter** [comment]
@lordmen99 Just update env.example file. #0c92cabc1ebfebf7a5038eed939a4b6c124ea36b
